# Wayle configuration file
imports = ["./colors.toml"]

[general]
font-sans = "Iosevka Nerd Font Propo"
font-mono = "Iosevka Nerd Font Propo"

[bar]
background-opacity = 95
scale = 0.9
button-variant = "basic"

[[bar.layout]]
monitor = "*"
show = true
left = [
    "hyprland-workspaces",
    "clock",
]
center = ["window-title"]
right = [
    "keyboard-input",
    "brightness",
    "volume",
    "network",
    "bluetooth",
    "battery",
    "idle-inhibit",
    "power",
]

[modules.hyprland-workspaces]
min-workspace-count = 5

[modules.keyboard-input]
left-click = "hyprctl switchxkblayout current next"

[modules.power]
left-click = "wlogout"

[wallpaper]
engine-enabled = false
