#!/bin/bash

# function that attempts to install a package if it is not already installed
# exits the program with an error if install fails
try_install() {
    if command -v $1 &> /dev/null; then
        echo "$1 is installed. Skipping..."
    else
        echo "No $1. Installing..."
        if ! sudo $PKG_INSTALL $1; then
            echo "Failed to install $1."
            echo "Please manually install it and restart the script."
            exit 1
        fi
        echo ""
    fi
}

nvim_setup() {
    # packer install
    git clone --depth 1 https://github.com/wbthomason/packer.nvim\
    ~/.local/share/nvim/site/pack/packer/start/packer.nvim

    # syncing packer
    nvim --headless -c ":PackerSync" -c "quitall"
}

echo "------------------------------ BOOTSTRAPPER ------------------------------"
echo ""

# Package manager inputs
read -p "Tell me your package manager. " PKG
read -p "What's $PKGMGR's install command? E.g. pacman -S for pacman. " PKG_INSTALL
read -p "What's $PKGMGR's update command? E.g pacman -Syu for pacman. If there
    is more than one command, for example in Ubuntu, connect them with && in the
    answer. " PKG_UPDATE

echo "Updating packages."
sudo $PKG_UPDATE
echo ""

try_install git
try_install curl
try_install fish
try_install neovim

echo "Installing additional utilities..."
sudo $PKGMGR_INSTALL git curl ripgrep fd exa bat tmux
echo ""

# starship
curl -sS https://starship.rs/install.sh | sh

# zoxide
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh\ 
    | bash

nvim_setup
