$image = /home/pes18fan/Pictures/walls/window.png
$primary = rgb(a0cafd)
$surface = rgb(101418)
$secondary = rgb(bac7db)
$error = rgb(ffb4ab)
$tertiary = rgb(d6bee4)
$on_surface = rgb(e1e2e8)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
