$primary = rgb(dfb8f6)
$surface = rgb(161217)
$secondary = rgb(d2c1d9)
$error = rgb(ffb4ab)
$tertiary = rgb(f4b7ba)
$surface_lowest = rgb(100d12)

background = $surface
accent = $primary
accent_secondary = $secondary
