format = "$username $character"

right_format = "$all"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[!](bold red)"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true
