background=121318ff
border-color=b7c4ffff

title-color=b7c4ffff
summary-color=e3e1e9ff
body-color=c6c5d0ff

progress-bar-color=b7c4ffff

min-width=10

border-size=2
border-radius=12

padding-horizontal=16
padding-vertical=14

# ------------------
# Low urgency
# ------------------

[low]
background=1a1b21ff
border-color=90909aff

title-color=90909aff
summary-color=c6c5d0ff
body-color=c6c5d0ff

# ------------------
# Normal urgency
# ------------------

[normal]
background=121318ff
border-color=b7c4ffff

# ------------------
# Critical urgency
# ------------------

[critical]
background=93000aff
border-color=ffb4abff

title-color=ffdad6ff
summary-color=ffdad6ff
body-color=ffdad6ff

progress-bar-color=ffb4abff
