background=141318ff
border-color=c9beffff

title-color=c9beffff
summary-color=e6e1e9ff
body-color=c9c5d0ff

progress-bar-color=c9beffff

min-width=10

border-size=2
border-radius=12

padding-horizontal=16
padding-vertical=14

# ------------------
# Low urgency
# ------------------

[low]
background=1c1b20ff
border-color=938f99ff

title-color=938f99ff
summary-color=c9c5d0ff
body-color=c9c5d0ff

# ------------------
# Normal urgency
# ------------------

[normal]
background=141318ff
border-color=c9beffff

# ------------------
# Critical urgency
# ------------------

[critical]
background=93000aff
border-color=ffb4abff

title-color=ffdad6ff
summary-color=ffdad6ff
body-color=ffdad6ff

progress-bar-color=ffb4abff
