background=101418ff
border-color=a0cafdff

title-color=a0cafdff
summary-color=e1e2e8ff
body-color=c3c7cfff

progress-bar-color=a0cafdff

min-width=10

border-size=2
border-radius=12

padding-horizontal=16
padding-vertical=14

# ------------------
# Low urgency
# ------------------

[low]
background=191c20ff
border-color=8d9199ff

title-color=8d9199ff
summary-color=c3c7cfff
body-color=c3c7cfff

# ------------------
# Normal urgency
# ------------------

[normal]
background=101418ff
border-color=a0cafdff

# ------------------
# Critical urgency
# ------------------

[critical]
background=93000aff
border-color=ffb4abff

title-color=ffdad6ff
summary-color=ffdad6ff
body-color=ffdad6ff

progress-bar-color=ffb4abff
